### ISSUE TITLE
Slim project build without Bitters and Neat

### ISSUE THREAD

**Issue by ryancoughlin** [thoughtbot/proteus-middleman#13]
I used Proteus for the first time on the Tropos iOS landing page. I find Bitters + Neat really heavy for most cases. It would be great to create a new project with Proteus and get deploy, live reload, sass, haml, etc But leave out Bitters and Neat.

I would be open to helping out in this. I havent taken a look at the source yet.

**Comment by joshuaogle** [comment]
We may eventually want a `new` command that can support options like this, but for now I included a page in the new wiki: https://github.com/thoughtbot/proteus-middleman/wiki/Removing-the-Bourbon-Suite

The other Proteus projects have a lot more included, but Middleman basically comes with your setup by default (just need to add Live Reload), which is one reason I like it so much.

Closing this issue, but I'm adding a new one to determine how best to do install options.
