### ISSUE TITLE
Clear thoughbot commits after run setup script

### ISSUE THREAD

**Issue by bernardogfilho** [thoughtbot/proteus-middleman#15]
Since the proteus user is creating a new project from a template, which is this repository, it wouldn't make sense to clear all commits from this repository after run the setup bash script?

**Comment by joshuaogle** [comment]
Thanks for the suggestion, @bernardogfilho! Added here: https://github.com/thoughtbot/proteus-middleman/commit/b7b1daf4e00005473bcc5eab1d2e906aaaefdb82

**Comment by bernardogfilho** [comment]
Great! :+1:
