### ISSUE TITLE
Add install options to customize setup

### ISSUE THREAD

**Issue by joshuaogle** [thoughtbot/proteus-middleman#16]
#13 brought up a good idea to include an option while installing so you can customize your Proteus Middleman setup. Some options might be:
- Whether or not to include Bourbon
- Some presets for Middleman Deploy
- Haml/Slim/Erb

I'm not sure how we could do that without adding a lot to the Proteus gem itself, but it's something to consider.

**Comment by jaronoff** [comment]
This would be great, as I'm messing with HAML and wasn't liking it and wanted to switch it out or do a fresh install with slim. Any thoughts on when this will be added, if at all?

**Comment by joshuaogle** [comment]
@jaronoff It wouldn't be hard to add, I just wasn't sure what people's preferences were for some of these.

I think it may be best to just remove Haml and provide easy instructions for how to set it up. While most of the designers here at thoughtbot do like to use Haml, [we haven't been able to agree](https://github.com/thoughtbot/guides/pull/366) on whether to default to it.

**Comment by jaronoff** [comment]
I started to rip out the haml stuff, and ran into a bunch of errors. I'm kind of green with all this stuff.

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
