### ISSUE TITLE
Add explanation of partials to the docs

### ISSUE THREAD

**Issue by joshuaogle** [thoughtbot/proteus-middleman#22]
Since we have the views in the `views` directory, you'll need to call all of your partials with `= partial 'views/_partial-name`

**Comment by cllns** [comment]
Also, can you explain what the views extension does? I don't know, so I typically remove it.

**Comment by joshuaogle** [comment]
Yes, that should go in the docs too. All it does is make it so you can have your views in a views directory rather than living at the project root.

**Comment by jaronoff** [comment]
+1

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
