### ISSUE TITLE
Error on middleman command

### ISSUE THREAD

**Issue by ljuboja** [thoughtbot/proteus-middleman#26]
/home/ljubisa/sites/gmwater/extensions/views.rb:2:in `<class:ViewsDirectory>': undefined method `register' for Middleman::Extensions::ViewsDirectory:Class (NoMethodError)

I got this error?

Thanx

**Comment by toobulkeh** [comment]
Fixed by https://github.com/thoughtbot/proteus-middleman/pull/25
