### ISSUE TITLE
The asset pipeline doesn't seem to work with middleman 4

### ISSUE THREAD

**Issue by guillehorno** [thoughtbot/proteus-middleman#28]
Hi! I found Proteus and looked awesome to prototype a new project I was going to do in Rails later.

I generated a proteus-middleman project using the proteus cli and from the get go (using ``proteus serve`` with the included code) the sass wasn't being compiled to css. I dug around a little more and looks like middleman doesn't provide an [asset pipeline any more](https://middlemanapp.com/advanced/asset_pipeline/)

I may be missing something, but spend quite some time and looks like that's the case :(

**Comment by joshuaogle** [comment]
Middleman 4's big changes broke a few things. I'm putting together an update for version 4 and hope to finish that up tomorrow. For today, it may be easiest to lock things to the latest version 3 release

**Comment by guillehorno** [comment]
Thanks! I'll try that then
